<a href="https://colab.research.google.com/github/Zennyth/itii-seance7/blob/master/Seance7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En utilisant numpy:

Ex 1 :Addition Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c{ij}=a{ij}+b_{ij}$

In [1]:
import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([ [9, 8, 7], [6, 5, 4], [3, 2, 1] ])

X = A+B
print("A : ",A)
print("B : ",B)
print("A + B : ",X)

A :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
B :  [[9 8 7]
 [6 5 4]
 [3 2 1]]
A + B :  [[10 10 10]
 [10 10 10]
 [10 10 10]]



Ex2 :Multiplication Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [38]:
import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([ [9, 8, 7], [6, 5, 4], [3, 2, 1] ])

# A = np.array([ [2, 1], [3, 2] ])
# B = np.array([ [1, -1], [1, 2] ])

def multiply(A, B):
  res = np.zeros((A.shape[0],B.shape[1]))
  if A.shape[1] == B.shape[0]:
    for i in range(A.shape[0]):
      for j in range(B.shape[1]):
        sum = 0
        for k in range(A.shape[1]):
          sum += A[i][k]*B[k][j]
        res[i][j] = sum
    return res
  else:
    print("Les deux matrices ne peuvent pas être multipliées")


print("A : ",A)
print("B : ",B)
print("A + B : ",multiply(A,B))

A :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
B :  [[9 8 7]
 [6 5 4]
 [3 2 1]]
A + B :  [[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]



Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non

In [ ]:
def isstochastique(P):
    nl = len(P)  # number of lines
    nc = len(P[0])  # number of columns
 
    state = True
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s > 1:
            state = False
            break
    return state
 
 
def isbistochastique(P):
    nl = len(P)  # number of lines
    nc = len(P[0])  # number of columns
 
    state = True 
    if(isstochastique(P)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s > 1:
                state = False
                break
    return state
 
 
def vecteurstable(G, h):
    nl = len(G)  # number of lines
    nc = len(G[0])  # number of columns
    state = True
    if(isstochastique(G)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i]*G[i][j]
            if s != h[j]:
                state = False
                break
    else:
        state = False
    return state


Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [41]:
A = np.array([ [1, -1], [1, 2] ])

def transpose(A):
  if A.shape[0] == 2 and A.shape[1] == 2:
    res = np.zeros((A.shape[0], A.shape[1]))
    res[0][1] = A[1][0]
    res[1][0] = A[0][1]
    res[1][1] = A[0][0]
    res[0][0] = A[1][1]
    return res
  else:
    print("Cette matrcie n'est pas au format 2*2")

print(transpose(A))

[[ 2.  1.]
 [-1.  1.]]



Ex 5: Permutations

$M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tous les éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matrice obtenue aura $co+1$ colonnes et $(n+1)$ $li$ lignes

Écrire toutes les permutations de(1, ..., n)

In [71]:
def permutation(M, n):
  l = M.shape[0]
  c = M.shape[1] + 1
  S = np.zeros((l*c, c))
  indexAll = 0
  for indexMatrice in range(c):
    for i in range(l):

      realJ = 0
      for j in range(c):
        if j == indexMatrice:
          S[indexAll][j] = n
        else:
          S[indexAll][j] = M[i][realJ]
          realJ+=1

      indexAll += 1
  return S

A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
permutation(A, 9)

array([[ 9.,  1.,  2.,  3.],
       [ 9.,  4.,  5.,  6.],
       [ 9.,  7.,  8.,  9.],
       [ 9., 10., 11., 12.],
       [ 9., 13., 14., 15.],
       [ 9., 16., 17., 18.],
       [ 1.,  9.,  2.,  3.],
       [ 4.,  9.,  5.,  6.],
       [ 7.,  9.,  8.,  9.],
       [10.,  9., 11., 12.],
       [13.,  9., 14., 15.],
       [16.,  9., 17., 18.],
       [ 1.,  2.,  9.,  3.],
       [ 4.,  5.,  9.,  6.],
       [ 7.,  8.,  9.,  9.],
       [10., 11.,  9., 12.],
       [13., 14.,  9., 15.],
       [16., 17.,  9., 18.],
       [ 1.,  2.,  3.,  9.],
       [ 4.,  5.,  6.,  9.],
       [ 7.,  8.,  9.,  9.],
       [10., 11., 12.,  9.],
       [13., 14., 15.,  9.],
       [16., 17., 18.,  9.]])